### ISSUE TITLE
亲测可以使用  但是文档写错了 

### ISSUE THREAD

**Issue by shen-lan** [daysai/egg-http-proxy-middleware#2]
Register
// {app_root}/middleware/proxy.js  ❌

// {app_root}/app/middleware/proxy.js  ✔
'use strict';

module.exports = require('egg-http-proxy-middleware');

**Comment by daysai** [comment]
> Register
> // {app_root}/middleware/proxy.js ❌
> 
> // {app_root}/app/middleware/proxy.js ✔
> 'use strict';
> 
> module.exports = require('egg-http-proxy-middleware');

感谢指正～可否有兴趣提个 mr ？

**Comment by daysai** [comment]
docs fixed
