### ISSUE TITLE
[ERROR] ECONNRESETError: read ECONNRESET

### ISSUE THREAD

**Issue by HowardTangOvO** [daysai/egg-http-proxy-middleware#3]
# 純粹的一起探討（借用了issue 感到抱歉）

之前在測試環境一直使用是沒有問題的，
最近上了PROD之後，發現并髮量大的時候會出現
```

[HPM] Proxy created: /xxx/proxy/xxxxapi  -> xxxxxxxx
[HPM] Proxy rewrite rule created: "^/xxx/proxy/xxxxap" ~> ""

2020-12-10 15:23:52 [ERROR] ECONNRESETError: read ECONNRESET
--
  | ECONNRESETError: read ECONNRESET
  | at TCP.onStreamRead (internal/stream_base_commons.js:205:27)
  | at TCP.callbackTrampoline (internal/async_hooks.js:120:14)
  | pid: 102
  |  
2020-12-10 15:23:52 [ERROR] ECONNRESETError: read ECONNRESET
--
  | ECONNRESETError: read ECONNRESET
  | at TCP.onStreamRead (internal/stream_base_commons.js:205:27)
  | at TCP.callbackTrampoline (internal/async_hooks.js:120:14)
  | pid: 96



```
一頭霧水
或許用`proxyRes.on('error')`能連接到該錯誤嗎？

**Comment by daysai** [comment]
> # 純粹的一起探討（借用了issue 感到抱歉）
> 之前在測試環境一直使用是沒有問題的，
> 最近上了PROD之後，發現并髮量大的時候會出現
> 
> ```
> 
> [HPM] Proxy created: /xxx/proxy/xxxxapi  -> xxxxxxxx
> [HPM] Proxy rewrite rule created: "^/xxx/proxy/xxxxap" ~> ""
> 
> 2020-12-10 15:23:52 [ERROR] ECONNRESETError: read ECONNRESET
> --
>   | ECONNRESETError: read ECONNRESET
>   | at TCP.onStreamRead (internal/stream_base_commons.js:205:27)
>   | at TCP.callbackTrampoline (internal/async_hooks.js:120:14)
>   | pid: 102
>   |  
> 2020-12-10 15:23:52 [ERROR] ECONNRESETError: read ECONNRESET
> --
>   | ECONNRESETError: read ECONNRESET
>   | at TCP.onStreamRead (internal/stream_base_commons.js:205:27)
>   | at TCP.callbackTrampoline (internal/async_hooks.js:120:14)
>   | pid: 96
> ```
> 
> 一頭霧水
> 或許用`proxyRes.on('error')`能連接到該錯誤嗎？

并发量有多大？然后可以贴下配置信息嘛？

**Comment by daysai** [comment]
PS：针对并发量大的场景，不建议在 node 层通过类似 http-proxy-middleware 的方式转发请求，可以考虑在外层比如 ingress / nginx 层增加接口转发逻辑，通常这样效率更高

**Comment by HowardTangOvO** [comment]
好像并不關并發的問題，反而是TIMEOUT的問題,把TIMEOUT時間調大了之後就沒有出現了
ps:其實我也是想用nginx做的..但是需要做一些log的操作 將in/out 記錄下來 :-(
////////////////////
我先將issue close了
