### ISSUE TITLE
关于中间件的疑问

### ISSUE THREAD

**Issue by zyl1314** [daysai/egg-http-proxy-middleware#4]
```
module.exports = () => {
  return async (ctx, next) => {
    console.log(1)
    await next()
    console.log(2)
  }
}
```
你好  上面这个中间件我放在了 egg-http-proxy-middleware 上面，可以正常的返回proxy后的内容   
console.log(1)执行了 console.log(2)没有执行   请问这是什么原因，谢谢

**Comment by daysai** [comment]
> ```
> module.exports = () => {
>   return async (ctx, next) => {
>     console.log(1)
>     await next()
>     console.log(2)
>   }
> }
> ```
> 
> 你好 上面这个中间件我放在了 egg-http-proxy-middleware 上面，可以正常的返回proxy后的内容
> console.log(1)执行了 console.log(2)没有执行 请问这是什么原因，谢谢

建议看下 egg 的中间件执行顺序文档：https://eggjs.github.io/zh/guide/middleware.html
