### ISSUE TITLE
post 请求不支持 csrf

### ISSUE THREAD

**Issue by zhengcaifeng** [daysai/egg-http-proxy-middleware#5]
![image](https://user-images.githubusercontent.com/27950890/136761046-8e53ca6c-cb7e-40ee-938c-a73c8dad7790.png)

**Comment by daysai** [comment]
这个中间件是 node 层的中间件，意思是后端接口配置上了 csrf ，node 层丢失了嘛？感觉可能不是中间件的问题

**Comment by zhengcaifeng** [comment]
> 这个中间件是 node 层的中间件，意思是后端接口配置上了 csrf ，node 层丢失了嘛？感觉可能不是中间件的问题
抱歉，是我请求的时候没有设置，谢谢
